### ISSUE TITLE
Nozzle and material choice boxes aren't visible.

### ISSUE THREAD

**Issue by GregValiant** [fieldOfView/Cura-SidebarGUIPlugin#38]
When clicking on the arrow to show the Nozzle size and Material selection boxes - the area remains blank.
5.1 on the left and 5.2 on the right.
![image](https://user-images.githubusercontent.com/64202104/193492211-59455493-7440-46e7-beec-23e16b599fad.png)

EDIT:
This is another strange view.  The extruder tabs appear twice.  I'm using the original package you put together.
![image](https://user-images.githubusercontent.com/64202104/193494753-3d83702c-c390-4a35-ad22-cd654c8bfac9.png)

**Comment by fieldOfView** [comment]
Thanks, fixed in https://github.com/fieldOfView/Cura-SidebarGUIPlugin/commit/48bad5e98812757ba47b6bec877912ed265a3feb

This sort of bug happens when in a new version of Cura QML elements are rearranged. In this case an element was removed, so instead of the material/nozzle selectors the plugin moved those extruder tabs there, which are right above the material/nozzle selectors in the original UI. See https://github.com/Ultimaker/Cura/commit/b7fd75b2dd202f2516f9188e342eccc8a15ae6ab

I missed that while checking for compatibility because I had the configuration collapsed.

**Comment by GregValiant** [comment]
After much pulling of hair and biting of fingernails I made the changes.  The fixes seem to be working fine.
