### ISSUE TITLE
[Feature Request] Floating sidebar !

### ISSUE THREAD

**Issue by yet-another-average-joe** [fieldOfView/Cura-SidebarGUIPlugin#4]
Hello, and thanks for this plugin.

(and waiting for 4.1 version)

The title could sound strange, as this plugin makes the sidebar not floating ! But maybe you coould add a feature that would allow the sidebar to be displayed out of the Cura window. This would be interresting for those who have multiple screens : Cura on one monitor, the sidebar on another.

**Comment by fieldOfView** [comment]
I finally have some progress to report on this request:
![image](https://user-images.githubusercontent.com/143551/107982617-a8ba8000-6fc4-11eb-81d1-dd12e892c7b0.png)
There's still some work to be done, most notably fixing how tooltips get displayed; currently they are drawn in the main window instead of in the toolpanel.

**Comment by yet-another-average-joe** [comment]
Can't believe it !
I've not been printing for 2 months. Today, I completed a design, ran Cura and first updated the plugins. At first I didn't notice the small buttons in the sidebar. And finally played with them : what are they ??? And discovered that the sidebar can now be undocked and moved to another monitor !
Many thanks ! This is the greatest Cura GUI enhancement ever. A life changer. It virtually doubles the viewport area when tweaking the options.

**Comment by fieldOfView** [comment]
It took me a little while, but I got there in the end.
